services:
  db:
    image: postgres:16
    container_name: helium
    environment:
      POSTGRES_DB: heliumdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - helium_pg:/var/lib/postgresql/data

volumes:
  helium_pg:
